%% Setup

init_quarter_car

project_folder = fileparts(mfilename('fullpath'));
model_name = bdroot;

if isempty(model_name) || strcmp(model_name,'simulink')
    error('Open the quarter-car Simulink model first.')
end

results_folder = fullfile(project_folder,...
    'results','ride_comfort');

figures_folder = fullfile(project_folder,...
    'figures','ride_comfort');

if ~exist(results_folder,'dir')
    mkdir(results_folder)
end

if ~exist(figures_folder,'dir')
    mkdir(figures_folder)
end

%% Road cases

road_names = {'step',...
              'speed_bump',...
              'sine',...
              'random'};

road_labels = {'Step',...
               'Speed Bump',...
               'Sinusoidal',...
               'Random Class C'};

evaluation_start = [1.0 1.0 3.0 1.5];
evaluation_end = [5.0 5.0 10.0 10.0];

n_cases = numel(road_names);

body_accel_rms = zeros(n_cases,1);
body_accel_peak = zeros(n_cases,1);
crest_factor = zeros(n_cases,1);

susp_travel_rms = zeros(n_cases,1);
tyre_force_rms = zeros(n_cases,1);

dynamic_load_coefficient = zeros(n_cases,1);
minimum_total_tyre_force = zeros(n_cases,1);

contact_status = cell(n_cases,1);

%% Simulations

for k = 1:n_cases

    road_case = k;

    sim_out = sim(model_name,'StopTime','10');

    sim_ts = sim_out.sim_data;
    t = sim_ts.Time;
    y = sim_ts.Data;

    range = t >= evaluation_start(k) & ...
            t <= evaluation_end(k);

    te = t(range);

    body_accel = y(range,4);
    susp_travel = y(range,5);
    tyre_force = y(range,6);

    duration = te(end) - te(1);

    body_accel_rms(k) = sqrt(...
        trapz(te,body_accel.^2)/duration);

    body_accel_peak(k) = max(abs(body_accel));

    crest_factor(k) = ...
        body_accel_peak(k)/body_accel_rms(k);

    susp_travel_rms(k) = 1000*sqrt(...
        trapz(te,susp_travel.^2)/duration);

    tyre_force_rms(k) = sqrt(...
        trapz(te,tyre_force.^2)/duration);

    dynamic_load_coefficient(k) = ...
        tyre_force_rms(k)/Fz0;

    minimum_total_tyre_force(k) = ...
        Fz0 + min(tyre_force);

    if minimum_total_tyre_force(k) > 0
        contact_status{k} = 'Maintained';
    else
        contact_status{k} = 'Lost';
    end

    if k == 4
        random_t = t;
        random_y = y;
    end
end

%% Comfort summary

summary = table(road_names',...
                evaluation_start',...
                evaluation_end',...
                body_accel_rms,...
                body_accel_peak,...
                crest_factor,...
                susp_travel_rms,...
                tyre_force_rms,...
                dynamic_load_coefficient,...
                minimum_total_tyre_force,...
                contact_status,...
    'VariableNames',{'RoadProfile',...
                     'EvaluationStart_s',...
                     'EvaluationEnd_s',...
                     'BodyAccelRMS_m_s2',...
                     'PeakBodyAccel_m_s2',...
                     'CrestFactor',...
                     'SuspTravelRMS_mm',...
                     'DynamicTyreForceRMS_N',...
                     'DynamicLoadCoefficient',...
                     'MinimumTotalTyreForce_N',...
                     'TyreContact'});

writetable(summary,...
    fullfile(results_folder,'ride_comfort_summary.csv'));

%% Random-road response

random_response = table(random_t,...
                        random_y(:,1),...
                        random_y(:,2),...
                        random_y(:,3),...
                        random_y(:,4),...
                        random_y(:,5),...
                        random_y(:,6),...
                        Fz0 + random_y(:,6),...
    'VariableNames',{'Time_s',...
                     'Road_m',...
                     'BodyDisp_m',...
                     'WheelDisp_m',...
                     'BodyAccel_m_s2',...
                     'SuspTravel_m',...
                     'DynamicTyreForce_N',...
                     'TotalTyreForce_N'});

writetable(random_response,...
    fullfile(results_folder,...
    'random_road_vehicle_response.csv'));

%% Random-road figure

fig = figure('Visible','off',...
             'Color','w',...
             'Position',[100 50 1050 900]);

layout = tiledlayout(fig,4,1,...
                     'TileSpacing','compact',...
                     'Padding','compact');

nexttile
plot(random_t,1000*random_y(:,1),...
    'Color',[0.15 0.35 0.65],...
    'LineWidth',1.1)
grid on
xlim([0.8 10])
ylabel('Road (mm)')
title('Random Road Profile')

nexttile
plot(random_t,random_y(:,4),...
    'Color',[0.85 0.33 0.10],...
    'LineWidth',1.1)
grid on
xlim([0.8 10])
ylabel('Acceleration (m/s^2)')
title('Body Acceleration')

nexttile
plot(random_t,1000*random_y(:,5),...
    'Color',[0.49 0.18 0.56],...
    'LineWidth',1.1)
grid on
xlim([0.8 10])
ylabel('Travel (mm)')
title('Suspension Travel')

nexttile
plot(random_t,random_y(:,6),...
    'Color',[0.47 0.67 0.19],...
    'LineWidth',1.1)
grid on
xlim([0.8 10])
xlabel('Time (s)')
ylabel('Force (N)')
title('Dynamic Tyre Force')

title(layout,...
    'Passive Suspension Response to ISO 8608 Class C Road',...
    'FontWeight','bold')

set(findall(fig,'-property','FontName'),...
    'FontName','Times New Roman')

exportgraphics(fig,...
    fullfile(figures_folder,...
    'random_road_vehicle_response.png'),...
    'Resolution',300);

close(fig)

%% RMS comparison figure

fig = figure('Visible','off',...
             'Color','w',...
             'Position',[100 100 850 520]);

bar_handle = bar(body_accel_rms,...
                 'FaceColor','flat');

bar_handle.CData = [0.20 0.45 0.75
                    0.90 0.45 0.15
                    0.55 0.30 0.65
                    0.25 0.65 0.40];

grid on
xticks(1:n_cases)
xticklabels(road_labels)
xtickangle(15)

ylabel('RMS Body Acceleration (m/s^2)')
title('Ride-Comfort Comparison')

value_offset = 0.03*max(body_accel_rms);

for k = 1:n_cases
    text(k,...
         body_accel_rms(k) + value_offset,...
         sprintf('%.3f',body_accel_rms(k)),...
         'HorizontalAlignment','center');
end

ylim([0 1.2*max(body_accel_rms)])

set(gca,'FontName','Times New Roman')

exportgraphics(fig,...
    fullfile(figures_folder,...
    'body_acceleration_rms_comparison.png'),...
    'Resolution',300);

close(fig)

road_case = 1;

disp(summary)