%% Passive and active suspension comparison
% Run this script while the quarter-car Simulink model is open.

clc
init_quarter_car

project_folder = fileparts(mfilename('fullpath'));

if isempty(project_folder)
    project_folder = pwd;
end

%% Find the open Simulink model

model_name = '';

try
    current_system = gcs;

    if ~isempty(current_system)
        model_name = bdroot(current_system);
    end
catch
    model_name = '';
end

if isempty(model_name) || strcmp(model_name,'simulink')

    open_models = find_system(...
        'SearchDepth',0,...
        'Type','block_diagram');

    open_models = open_models(...
        ~strcmp(open_models,'simulink'));

    if isempty(open_models)

        error(['Open the completed quarter-car Simulink model ',...
               'before running this script.'])

    elseif numel(open_models) > 1

        error(['More than one Simulink model is open. ',...
               'Select the quarter-car model and run again.'])
    end

    model_name = open_models{1};
end

fprintf('Model used: %s\n',model_name)

%% Output folders

results_folder = fullfile(...
    project_folder,...
    'results',...
    'active_suspension');

figures_folder = fullfile(...
    project_folder,...
    'figures',...
    'active_suspension');

if ~exist(results_folder,'dir')
    mkdir(results_folder)
end

if ~exist(figures_folder,'dir')
    mkdir(figures_folder)
end

%% Road cases and evaluation windows

road_names = [
    "step"
    "speed_bump"
    "sine"
    "random_class_c"
];

road_labels = [
    "Step"
    "Speed Bump"
    "Sinusoidal"
    "Random Class C"
];

% Evaluation intervals used for calculating performance metrics

evaluation_start = [
    1.0
    1.0
    3.0
    1.5
];

evaluation_end = [
    5.0
    5.0
    10.0
    10.0
];

n_cases = numel(road_names);
n_metrics = 13;

passive_metrics = nan(n_cases,n_metrics);
active_metrics  = nan(n_cases,n_metrics);

road_input_difference = nan(n_cases,1);

passive_contact = strings(n_cases,1);
active_contact  = strings(n_cases,1);

raw_results = struct([]);

%% Run passive and active simulations

for k = 1:n_cases

    fprintf('\nRunning road case %d of %d: %s\n',...
        k,n_cases,road_labels(k))

    assignin('base','road_case',k)

    %% Passive suspension

    assignin('base','active_mode',0)

    passive_out = sim(...
        model_name,...
        'StopTime','10');

    [tp,yp] = read_sim_data(passive_out);

    %% Active PID suspension

    assignin('base','active_mode',1)

    active_out = sim(...
        model_name,...
        'StopTime','10');

    [ta,ya] = read_sim_data(active_out);

    %% Check output structure

    if size(yp,2) < 6 || size(ya,2) < 6

        error(['sim_data must contain at least six columns:',newline,...
               '1. Road input',newline,...
               '2. Body displacement',newline,...
               '3. Wheel displacement',newline,...
               '4. Body acceleration',newline,...
               '5. Suspension travel',newline,...
               '6. Dynamic tyre force'])
    end

    %% Calculate performance metrics

    passive_metrics(k,:) = calculate_metrics(...
        tp,...
        yp,...
        evaluation_start(k),...
        evaluation_end(k),...
        Fz0);

    active_metrics(k,:) = calculate_metrics(...
        ta,...
        ya,...
        evaluation_start(k),...
        evaluation_end(k),...
        Fz0);

    %% Check tyre–road contact

    if passive_metrics(k,11) > 0
        passive_contact(k) = "Maintained";
    else
        passive_contact(k) = "Lost";
    end

    if active_metrics(k,11) > 0
        active_contact(k) = "Maintained";
    else
        active_contact(k) = "Lost";
    end

    %% Align active data with passive time vector

    ya_common = align_to_time(...
        ta,...
        ya,...
        tp);

    road_input_difference(k) = ...
        max(abs(yp(:,1) - ya_common(:,1)));

    if road_input_difference(k) > 1e-8

        warning(['Passive and active road inputs differ for %s. ',...
                 'Check the random-road seed or input source.'],...
                 road_labels(k))
    end

    %% Save complete time-history response as CSV

    response = table(...
        tp,...
        yp(:,1),...
        ya_common(:,1),...
        yp(:,2),...
        ya_common(:,2),...
        yp(:,3),...
        ya_common(:,3),...
        yp(:,4),...
        ya_common(:,4),...
        yp(:,5),...
        ya_common(:,5),...
        yp(:,6),...
        ya_common(:,6),...
        Fz0 + yp(:,6),...
        Fz0 + ya_common(:,6),...
        'VariableNames',{...
        'Time_s',...
        'PassiveRoad_m',...
        'ActiveRoad_m',...
        'PassiveBodyDisp_m',...
        'ActiveBodyDisp_m',...
        'PassiveWheelDisp_m',...
        'ActiveWheelDisp_m',...
        'PassiveBodyAccel_m_s2',...
        'ActiveBodyAccel_m_s2',...
        'PassiveSuspTravel_m',...
        'ActiveSuspTravel_m',...
        'PassiveDynamicTyreForce_N',...
        'ActiveDynamicTyreForce_N',...
        'PassiveTotalTyreForce_N',...
        'ActiveTotalTyreForce_N'});

    % If actuator force is column 7 of sim_data, save it too.

    if size(yp,2) >= 7 && size(ya_common,2) >= 7

        response.PassiveActuatorForce_N = yp(:,7);
        response.ActiveActuatorForce_N  = ya_common(:,7);
    end

    response_file = fullfile(...
        results_folder,...
        char(road_names(k) + ...
        "_active_passive_response.csv"));

    writetable(response,response_file);

    %% Store raw numerical results

    raw_results(k).RoadProfile = char(road_names(k));

    raw_results(k).EvaluationStart_s = ...
        evaluation_start(k);

    raw_results(k).EvaluationEnd_s = ...
        evaluation_end(k);

    raw_results(k).Passive.Time = tp;
    raw_results(k).Passive.Data = yp;

    raw_results(k).Active.Time = ta;
    raw_results(k).Active.Data = ya;

    %% Time-response comparison figure

    fig = figure(...
        'Visible','off',...
        'Color','w',...
        'Position',[100 50 1050 900]);

    layout = tiledlayout(...
        fig,...
        4,1,...
        'TileSpacing','compact',...
        'Padding','compact');

    % Body displacement

    nexttile

    plot(...
        tp,...
        1000*yp(:,2),...
        'k',...
        'LineWidth',1.1)

    hold on

    plot(...
        ta,...
        1000*ya(:,2),...
        'r',...
        'LineWidth',1.1)

    grid on
    xlim([0.8 10])

    ylabel('Body disp. (mm)')
    title('Body Displacement')

    legend(...
        'Passive',...
        'Active PID',...
        'Location','best')

    % Body acceleration

    nexttile

    plot(...
        tp,...
        yp(:,4),...
        'k',...
        'LineWidth',1.1)

    hold on

    plot(...
        ta,...
        ya(:,4),...
        'r',...
        'LineWidth',1.1)

    grid on
    xlim([0.8 10])

    ylabel('Acceleration (m/s^2)')
    title('Body Acceleration')

    % Suspension travel

    nexttile

    plot(...
        tp,...
        1000*yp(:,5),...
        'k',...
        'LineWidth',1.1)

    hold on

    plot(...
        ta,...
        1000*ya(:,5),...
        'r',...
        'LineWidth',1.1)

    grid on
    xlim([0.8 10])

    ylabel('Travel (mm)')
    title('Suspension Travel')

    % Dynamic tyre force

    nexttile

    plot(...
        tp,...
        yp(:,6),...
        'k',...
        'LineWidth',1.1)

    hold on

    plot(...
        ta,...
        ya(:,6),...
        'r',...
        'LineWidth',1.1)

    grid on
    xlim([0.8 10])

    xlabel('Time (s)')
    ylabel('Force (N)')
    title('Dynamic Tyre Force')

    title(...
        layout,...
        sprintf(...
        'Passive and Active Suspension: %s Input',...
        road_labels(k)),...
        'FontWeight','bold')

    set(...
        findall(fig,'-property','FontName'),...
        'FontName','Times New Roman')

    figure_file = fullfile(...
        figures_folder,...
        char(road_names(k) + ...
        "_active_passive_comparison.png"));

    exportgraphics(...
        fig,...
        figure_file,...
        'Resolution',300);

    close(fig)
end

%% Calculate percentage changes
% A positive value means improvement/reduction.
% A negative value means that the active suspension increased the metric.

body_disp_reduction = percent_reduction(...
    passive_metrics(:,1),...
    active_metrics(:,1));

wheel_disp_reduction = percent_reduction(...
    passive_metrics(:,2),...
    active_metrics(:,2));

body_accel_rms_reduction = percent_reduction(...
    passive_metrics(:,3),...
    active_metrics(:,3));

peak_body_accel_reduction = percent_reduction(...
    passive_metrics(:,4),...
    active_metrics(:,4));

susp_travel_rms_reduction = percent_reduction(...
    passive_metrics(:,6),...
    active_metrics(:,6));

tyre_force_rms_reduction = percent_reduction(...
    passive_metrics(:,8),...
    active_metrics(:,8));

%% Complete summary table

summary = table(...
    road_names,...
    evaluation_start,...
    evaluation_end,...
    road_input_difference,...
    passive_metrics(:,1),...
    active_metrics(:,1),...
    body_disp_reduction,...
    passive_metrics(:,2),...
    active_metrics(:,2),...
    wheel_disp_reduction,...
    passive_metrics(:,3),...
    active_metrics(:,3),...
    body_accel_rms_reduction,...
    passive_metrics(:,4),...
    active_metrics(:,4),...
    peak_body_accel_reduction,...
    passive_metrics(:,5),...
    active_metrics(:,5),...
    passive_metrics(:,6),...
    active_metrics(:,6),...
    susp_travel_rms_reduction,...
    passive_metrics(:,7),...
    active_metrics(:,7),...
    passive_metrics(:,8),...
    active_metrics(:,8),...
    tyre_force_rms_reduction,...
    passive_metrics(:,9),...
    active_metrics(:,9),...
    passive_metrics(:,10),...
    active_metrics(:,10),...
    passive_metrics(:,11),...
    active_metrics(:,11),...
    passive_contact,...
    active_contact,...
    'VariableNames',{...
    'RoadProfile',...
    'EvaluationStart_s',...
    'EvaluationEnd_s',...
    'RoadInputMaxDifference_m',...
    'PassiveBodyDispRMS_mm',...
    'ActiveBodyDispRMS_mm',...
    'BodyDispReduction_percent',...
    'PassiveWheelDispRMS_mm',...
    'ActiveWheelDispRMS_mm',...
    'WheelDispReduction_percent',...
    'PassiveBodyAccelRMS_m_s2',...
    'ActiveBodyAccelRMS_m_s2',...
    'BodyAccelRMSReduction_percent',...
    'PassivePeakBodyAccel_m_s2',...
    'ActivePeakBodyAccel_m_s2',...
    'PeakBodyAccelReduction_percent',...
    'PassiveCrestFactor',...
    'ActiveCrestFactor',...
    'PassiveSuspTravelRMS_mm',...
    'ActiveSuspTravelRMS_mm',...
    'SuspTravelRMSReduction_percent',...
    'PassivePeakSuspTravel_mm',...
    'ActivePeakSuspTravel_mm',...
    'PassiveDynamicTyreForceRMS_N',...
    'ActiveDynamicTyreForceRMS_N',...
    'TyreForceRMSReduction_percent',...
    'PassivePeakDynamicTyreForce_N',...
    'ActivePeakDynamicTyreForce_N',...
    'PassiveDynamicLoadCoefficient',...
    'ActiveDynamicLoadCoefficient',...
    'PassiveMinimumTotalTyreForce_N',...
    'ActiveMinimumTotalTyreForce_N',...
    'PassiveTyreContact',...
    'ActiveTyreContact'});

% Include actuator-force statistics when Fa is column 7.

if all(~isnan(active_metrics(:,12)))

    summary.ActiveActuatorForceRMS_N = ...
        active_metrics(:,12);

    summary.ActivePeakActuatorForce_N = ...
        active_metrics(:,13);
end

writetable(...
    summary,...
    fullfile(...
    results_folder,...
    'active_passive_summary.csv'));

% Save random-road summary separately.

writetable(...
    summary(4,:),...
    fullfile(...
    results_folder,...
    'random_road_active_passive_summary.csv'));

%% Compact random-road table for the report

random_index = 4;

metric = [
    "Body acceleration RMS"
    "Peak body acceleration"
    "Suspension travel RMS"
    "Dynamic tyre force RMS"
];

unit = [
    "m/s^2"
    "m/s^2"
    "mm"
    "N"
];

passive_value = [
    passive_metrics(random_index,3)
    passive_metrics(random_index,4)
    passive_metrics(random_index,6)
    passive_metrics(random_index,8)
];

active_value = [
    active_metrics(random_index,3)
    active_metrics(random_index,4)
    active_metrics(random_index,6)
    active_metrics(random_index,8)
];

reduction_percent = percent_reduction(...
    passive_value,...
    active_value);

random_road_key_metrics = table(...
    metric,...
    unit,...
    passive_value,...
    active_value,...
    reduction_percent,...
    'VariableNames',{...
    'Metric',...
    'Unit',...
    'Passive',...
    'ActivePID',...
    'Reduction_percent'});

writetable(...
    random_road_key_metrics,...
    fullfile(...
    results_folder,...
    'random_road_key_metrics.csv'));

%% Save PID controller settings

parameter = [
    "Proportional gain"
    "Integral gain"
    "Derivative gain"
    "Derivative filter coefficient"
    "Actuator force limit"
];

symbol = [
    "Kp"
    "Ki"
    "Kd"
    "N"
    "Fa_max"
];

value = [
    Kp_pid
    Ki_pid
    Kd_pid
    N_pid
    Fa_max
];

unit = [
    "N/m"
    "N/(m.s)"
    "N.s/m"
    "-"
    "N"
];

pid_parameters = table(...
    parameter,...
    symbol,...
    value,...
    unit);

writetable(...
    pid_parameters,...
    fullfile(...
    results_folder,...
    'pid_controller_parameters.csv'));

%% Summary figure for the four main performance measures

fig = figure(...
    'Visible','off',...
    'Color','w',...
    'Position',[100 70 1150 780]);

layout = tiledlayout(...
    fig,...
    2,2,...
    'TileSpacing','compact',...
    'Padding','compact');

% RMS body acceleration

nexttile

bar(...
    [passive_metrics(:,3),...
     active_metrics(:,3)],...
    'grouped')

grid on
xticks(1:n_cases)
xticklabels(road_labels)
xtickangle(15)

ylabel('RMS acceleration (m/s^2)')
title('Body Acceleration RMS')

legend(...
    'Passive',...
    'Active PID',...
    'Location','best')

% Peak body acceleration

nexttile

bar(...
    [passive_metrics(:,4),...
     active_metrics(:,4)],...
    'grouped')

grid on
xticks(1:n_cases)
xticklabels(road_labels)
xtickangle(15)

ylabel('Peak acceleration (m/s^2)')
title('Peak Body Acceleration')

% RMS suspension travel

nexttile

bar(...
    [passive_metrics(:,6),...
     active_metrics(:,6)],...
    'grouped')

grid on
xticks(1:n_cases)
xticklabels(road_labels)
xtickangle(15)

ylabel('RMS travel (mm)')
title('Suspension Travel RMS')

% RMS dynamic tyre force

nexttile

bar(...
    [passive_metrics(:,8),...
     active_metrics(:,8)],...
    'grouped')

grid on
xticks(1:n_cases)
xticklabels(road_labels)
xtickangle(15)

ylabel('RMS force (N)')
title('Dynamic Tyre Force RMS')

title(...
    layout,...
    'Passive and Active PID Suspension Performance',...
    'FontWeight','bold')

set(...
    findall(fig,'-property','FontName'),...
    'FontName','Times New Roman')

exportgraphics(...
    fig,...
    fullfile(...
    figures_folder,...
    'active_passive_metric_summary.png'),...
    'Resolution',300);

close(fig)

%% Improvement and trade-off figure

key_reduction = [...
    body_accel_rms_reduction,...
    peak_body_accel_reduction,...
    susp_travel_rms_reduction,...
    tyre_force_rms_reduction];

fig = figure(...
    'Visible','off',...
    'Color','w',...
    'Position',[100 100 1050 560]);

bar(key_reduction','grouped')

hold on

yline(...
    0,...
    'k-',...
    'LineWidth',1.0)

grid on

xticks(1:4)

xticklabels({...
    'Body acceleration RMS',...
    'Peak body acceleration',...
    'Suspension travel RMS',...
    'Dynamic tyre force RMS'})

xtickangle(15)

ylabel('Reduction relative to passive (%)')
title('Active-Suspension Improvement and Trade-offs')

legend(...
    road_labels,...
    'Location','bestoutside')

set(...
    findall(fig,'-property','FontName'),...
    'FontName','Times New Roman')

exportgraphics(...
    fig,...
    fullfile(...
    figures_folder,...
    'active_suspension_improvement_percent.png'),...
    'Resolution',300);

close(fig)

%% Save all numerical data in one MAT file

save(...
    fullfile(...
    results_folder,...
    'active_passive_complete_results.mat'),...
    'raw_results',...
    'summary',...
    'random_road_key_metrics',...
    'pid_parameters',...
    'passive_metrics',...
    'active_metrics',...
    '-v7.3');

%% Restore model variables

road_case = 1;
active_mode = 0;

assignin('base','road_case',road_case)
assignin('base','active_mode',active_mode)

%% Display important random-road results

disp(' ')
disp('Random-road active/passive comparison:')
disp(random_road_key_metrics)

disp(' ')
disp('Complete summary:')
disp(summary)

fprintf('\nAll numerical results were saved in:\n%s\n',...
    results_folder)

fprintf('\nAll figures were saved in:\n%s\n',...
    figures_folder)

%% Local functions

function [t,y] = read_sim_data(sim_out)

    try
        sim_ts = sim_out.sim_data;
    catch
        error(['The simulation output does not contain sim_data. ',...
               'Check the To Workspace block or model output setting.'])
    end

    if ~isa(sim_ts,'timeseries')
        error('sim_data must be saved as a timeseries object.')
    end

    t = sim_ts.Time(:);
    y = squeeze(sim_ts.Data);

    if size(y,1) ~= numel(t) && ...
            size(y,2) == numel(t)

        y = y.';
    end

    if size(y,1) ~= numel(t)

        error(['The dimensions of sim_data.Time and ',...
               'sim_data.Data do not match.'])
    end
end

function values = calculate_metrics(...
    t,...
    y,...
    start_time,...
    end_time,...
    Fz0)

    range = ...
        t >= start_time & ...
        t <= end_time;

    if nnz(range) < 2

        error(['Not enough samples are available ',...
               'in the evaluation interval.'])
    end

    te = t(range);
    ye = y(range,:);

    duration = te(end) - te(1);

    time_rms = @(x) ...
        sqrt(trapz(te,x.^2)/duration);

    body_disp_rms = ...
        1000*time_rms(ye(:,2));

    wheel_disp_rms = ...
        1000*time_rms(ye(:,3));

    body_accel_rms = ...
        time_rms(ye(:,4));

    peak_body_accel = ...
        max(abs(ye(:,4)));

    if body_accel_rms > eps

        crest_factor = ...
            peak_body_accel/body_accel_rms;
    else
        crest_factor = NaN;
    end

    susp_travel_rms = ...
        1000*time_rms(ye(:,5));

    peak_susp_travel = ...
        1000*max(abs(ye(:,5)));

    tyre_force_rms = ...
        time_rms(ye(:,6));

    peak_tyre_force = ...
        max(abs(ye(:,6)));

    dynamic_load_coefficient = ...
        tyre_force_rms/Fz0;

    minimum_total_tyre_force = ...
        Fz0 + min(ye(:,6));

    actuator_force_rms = NaN;
    peak_actuator_force = NaN;

    if size(ye,2) >= 7

        actuator_force_rms = ...
            time_rms(ye(:,7));

        peak_actuator_force = ...
            max(abs(ye(:,7)));
    end

    values = [...
        body_disp_rms,...
        wheel_disp_rms,...
        body_accel_rms,...
        peak_body_accel,...
        crest_factor,...
        susp_travel_rms,...
        peak_susp_travel,...
        tyre_force_rms,...
        peak_tyre_force,...
        dynamic_load_coefficient,...
        minimum_total_tyre_force,...
        actuator_force_rms,...
        peak_actuator_force];
end

function aligned_data = align_to_time(...
    source_time,...
    source_data,...
    target_time)

    same_size = ...
        numel(source_time) == numel(target_time);

    if same_size && ...
            max(abs(source_time(:)-target_time(:))) < 1e-12

        aligned_data = source_data;
    else
        aligned_data = interp1(...
            source_time,...
            source_data,...
            target_time,...
            'linear',...
            'extrap');
    end
end

function reduction = percent_reduction(...
    passive_value,...
    active_value)

    reduction = nan(size(passive_value));

    valid = ...
        abs(passive_value) > eps;

    reduction(valid) = ...
        100*(...
        passive_value(valid) - ...
        active_value(valid))./...
        passive_value(valid);
end